services:
  build:
    container_name: build
    build:
      dockerfile: build.dockerfile
    environment:
      - PROJECT_NAME=01009b90006dc000-exlaunch
    command:
      - ./exlaunch.sh
      - build
    volumes:
      - .:/work
    working_dir: /work
